### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by matcrobertson** [sdmiller1/tracker-app#3]
Problem Statement
--
Clear and consise on what the problem is
- [x] list what you plan on using to solve the problem
- [x] what will the rating scale be? (ie: stars, 10/10, Like/dislike)

Design documentation
--
Good consistency in your wireframes. It will make for a nice user experience
- [x] will you be adding a search functionality or do you scroll through?
- [x] consider picking out a color scheme that you want for your application

Database
--
Nice job challenging yourself with a semi-complex database
-	[x] add a visual of your database to your design documentation
-	[x] You were still unsure what exactly what it was going to look like. Feel free to bounce design ideas off me

Code
--
Good to see that you implemented the generic dao
-	[x] your H2 tag should be an h1 tag to meet WECAG standards
-	[x] have you considered Lombok?

**Comment by pawaitemadisoncollege** [comment]
@matcrobertson Are there any printlns or stack traces that should be replaced with logging?
